baseURL = "localhost:1313"
languageCode = "en-us"
title = "SaminYeasarArnob"
theme = "lodi"
#googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Alexis Collado, UX Designer"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "arnobsam@mila.quebec"
    #facebook = "lex.collado"
    #twitter = "lexiscollado"
    #dribbble = "alexiscollado"
    linkedin = "https://www.linkedin.com/in/samin-yeasar-arnob/"
    #medium = "ahvccollado"
    github = "https://github.com/SaminYeasar"
    googlescholar = "https://scholar.google.ca/citations?user=RMPv4RQAAAAJ&hl=en"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar__.jpg"
    subtitle = "Hi! This is Samin Yeasar Arnob. I am a Ph.D. student at McGill University."
    hero_right = ["I have started **Ph.D.** from January 2020 in **Computer Science** at **McGill University** under the supervision of [Dr. Doina Precup](https://www.linkedin.com/in/doina-precup-1ba61314/?originalSubdomain=ca) at [Reasoning and learning lab (rllab)](http://rl.cs.mcgill.ca/) and at [Mila](https://mila.quebec/en/).**", 
		"I have completed my **Masters** from **Electrical and Computer Engineering** at **McGill University**.  My master’s research was on **Adversarial Inverse Reinforcement Learning** under the supervision of [Dr. Aditya Mahajan](http://www.ece.mcgill.ca/~amahaj1/) at System and Control Group.", 
		"I have also worked at **Mila** as an **intern** with **Dr. Doina Precup** on NeurIPS MineRL competition 2019, where we explore learning transferable skills over multiple environments from MineCraft gaming environment using imitation learning", 
		"I completed my Under-graduation from Islamic University of Technology (IUT), Bangladesh. I had the pleasure to work on **Computational Nano-photonics** and was supervised by [Dr. Md. Ruhul Amin](https://scholar.google.com/citations?user=flcwae0AAAAJ&hl=en) and co-supervised by [Dr. Rakibul Hasan Sagor](https://scholar.google.com/citations?user=6gyN_V0AAAAJ&hl=en)."]
    resume = "Single_Page_CV_2"


# ==== TODO ==== #
[params.process]
    enable = false
    title = "My Process"
    subtitle = "Full Process Design"

[params.case_studies]
    enable = false
    title = "Case Studies"
    subtitle = "Selected Works"

[params.footer]
    enable = true
